// Top-level constant for default values
export const DEFAULT_VALUES = [
  "ACCEPTANCE",
  "ACCURACY",
  "ACHIEVEMENT",
  "ADVENTURE",
  "ATTRACTIVENESS",
  "AUTHORITY",
  "AUTONOMY",
  "BEAUTY",
  "CARING",
  "CHALLENGE",
  "CHANGE",
  // "COMFORT",
  // "COMMITMENT",
  // "COMPASSION",
  // "CONTRIBUTION",
  // "COOPERATION",
  // "COURTESY",
  // "CREATIVITY",
  // "DEPENDABILITY",
  // "DUTY",
  // "ECOLOGY",
  // "EXCITEMENT",
  // "FAITHFULNESS",
  // "FAME",
  // "FAMILY",
  // "FITNESS",
  // "FLEXIBILITY",
  // "FORGIVENESS",
  // "FRIENDSHIP",
  // "FUN",
  // "GENEROSITY",
  // "GENUINENESS",
  // "GOD'S WILL",
  // "GROWTH",
  // "HEALTH",
  // "HELPFULNESS",
  // "HONESTY",
  // "HOPE",
  // "HUMILITY",
  // "HUMOR",
  // "INDEPENDENCE",
  // "INDUSTRY",
  // "INNER PEACE",
  // "INTIMACY",
  // "JUSTICE",
  // "KNOWLEDGE",
  // "LEISURE",
  // "LOVED",
  // "LOVING",
  // "MASTERY",
  // "MINDFULNESS",
  // "MODERATION",
  // "MONOGAMY",
  // "NONCONFORMITY",
  // "NURTURANCE",
  // "OPENNESS",
  // "ORDER",
  // "PASSION",
  // "PLEASURE",
  // "POPULARITY",
  // "POWER",
  // "PURPOSE",
  // "RATIONALITY",
  // "REALISM",
  // "RESPONSIBILITY",
  // "RISK",
  // "ROMANCE",
  // "SAFETY",
  // "SELF-ACCEPTANCE",
  // "SELF-CONTROL",
  // "SELF-ESTEEM",
  // "SELF-KNOWLEDGE",
  // "SERVICE",
  // "SEXUALITY",
  // "SIMPLICITY",
  // "SOLITUDE",
  // "SPIRITUALITY",
  // "STABILITY",
  // "TOLERANCE",
  // "TRADITION",
  // "VIRTUE",
  // "WEALTH",
  // "WORLD PEACE",
]; 
